### ISSUE TITLE
User account database

### ISSUE THREAD

**Issue by mangkoran** [t-analog/crowdfinder-client#8]
User account schema:
```yaml
User:
  type: object
  properties:
    user_id:
      type: string
    user_email:
      type: string
    user_password:
      type: string
```
